language: android
env:
  global:
  - BUILD_TOOLS=26.0.2
  - ANDROID_SDK=26
  - secure: 2DKJSx0H9YSrvkGuF3nGTXA4qZZZs0Mnj3axD12CvE4AUXPMiwQheSeh5Dwd3W0LV6XfmUI6/nZhZf8I+BJObpBTMV6+Swgt1OR/5A8uksJCbUnsOEHBvhdaZgj9tnbM6KfNUqtJnd/E+/iz8XmuU7CJLT7mR750ERqTwj3aTeFZ7yAJn2tD0Zio+CH9V3Vrs3mTIPYkwFpcdcuikKA0Ix04t1K+3+nEeUPusp8/v+v2ViKYEGdfmxFsHcKHAAVpqgXQzGSfkCMEMpfGP+8T4Y7vfPzgO1KyJm6+3FPMN6+6qJBHcvQz77y9ZQE6z/b29ih4xhxHtyhH8R8l2IT6v46JPuQzg+4YkHpDYJye4ffpmYFqgZaTwYaNcktX2ia6bQgqPtvIDfyGJQ0XMClQhZyOlR5ksClYeypGgZgA6i3V2Zrlsc89a8TgmD6UUEUd28utghuBERff9pBML267eZQ1ylex497Fpt6/YXZATuZG7mPWGMJx3Dr/IhKIbvEcZiqM3JsE7+gnOi7LK9UCXC56jzXhvYt5TH8pWJvZ2w3yL4okKuF4OXDgSG5StCJUlMY0YyJ148LdxAPsF3uxkCYDXuKQK+3J7qA4gGoURlta/KPNNJTvurOkxZXKr+HPPMNwwwo1ofPDQx0JtgmbH6te6yZ/LeuQ2d/ZS/LFjh8=
  - secure: UIs6ZiHdo2KP3+6n2VRKLb1sTQELexQG4Lk34/Dlxj7tGLYTmW7gVQqNnFMuHZAfZvx72cBEC/X5XiVb38fp9saj23AStqokVmEz2ACH0MWXPZzYpfz/cY0oxFoI+TiOiShzbdTh/E6av7rhjmvssqa4bEkECHxFOYtRKm41lMM8vBFK6IHj45uqCl4NxavLtTvvT1gRBpsmILmjh4B25W3HAPdW2+twitR5hS4pYxhm1BEjJRNvFMSqzQFywgZqE2ViMa47KHAE1KV2mMsluguLJzy4u3vvpYB2nhIX8qT294ozzokoy5vPst2TGL9etIyERqO+SlizReFe6JORByOCa9nZmxhYjwZADwGtUHeS9+fy+s9AS7JihC4V5yAwypMIZxVeRmiOz88Z53YnnIn4p6Gi8ZGJUmWBV05cg6MHC8T3J0hMh4WqGBag2nhOXMBZ+Tmu38CVEkHN83x8spbjE4ZuUi77m3fXVdIIRcb/YkVrdidXbg5gDmlh18POHya5garPn9lRPkc9gmIZi9sNBuBAbRu1BOkDXrJjoL7NTlUJwP6RMnL1EzXeAD2KnOOLN4jGOD/uUF2CA12KYmug5Y43ER9TUd/6rDGgT2ZI2uEiTJ6Vbqx8lAcUCJ6JY9m/4sU3sTAvf+z7B6/N1ixh4hlkwb1/TAk1eNb2U60=
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-$BUILD_TOOLS
  - android-$ANDROID_SDK
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- mkdir "${ANDROID_HOME}/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "${ANDROID_HOME}/licenses/android-sdk-preview-license"
- sleep 10
- chmod +x gradlew
before_deploy:
- openssl aes-256-cbc -K $encrypted_eee74906dbb4_key -iv $encrypted_eee74906dbb4_iv -in keystore.jks.enc -out keystore.jks -d
- cp $TRAVIS_BUILD_DIR/keystore.jks $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk iotaKey
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/26.0.2/zipalign -v 4 app-release-unsigned.apk app-release.apk"
deploy:
  provider: releases
  api_key:
    secure: 4PDAAxa+Q1C1wLcJ97FZY/eK7UkuGKJU4UIzWqUw8Bbvq6BPFnWPLH5uUZhO2IDwJmFVfBkaWwndddVqxz2ZGAzheALwmgm9AAJjGcaZKhK8+/DxUi4IWv42cCRce5ow34i0LgV7ltyXhbEtToQDwTIYE24Liil1baDvNC70dUz9o9GNbZNxUttIXCKNTQDrSR3LmBefdCq9suBDj0jtLuMdav333cfLKadaOBrumFcS3HMzo1MjQ5bNJpDsBmAMvQRvLzEH+sSrJJbWI5Ks820BLmz0clD81ti07mOvtiWCZ8tl+VHH34aJvtDqqkUIwBst5iKYc8FIq1dIrI6dJOhxiEfblY0n9+WacW7Zcg3EZQkPqBbeewembX80uI1saLnqGLEQjFFqytKTeHKih2SmRm6rruBJPkll7XY/BQTw717/EbX8NUYNGsXoAod+q5Y78wCbMLLupeYicWAARgXN14Fo/e8aJl3ViIk4zMyMfAcaA/dRjqTHpsu81+NfBy06dmlDaPk/eCNkkxZ4XSvntS1dkSlBUDoUIopyU/tO/ZizhOJoNJJpLZ4jARoXrfjt8TQwJg47SDggst+ZEcXCZaCZB0ziCmbEtfpJTLSt/C/6NlaVMTaYq7mQNslUWjPzbh0TZLXUs1Og4GK3IwYxYFEOSFBtmD9eILxVId0=
  file: app-release.apk
  skip_cleanup: true
  on:
    branch: master
    repo: iotaledger/android-wallet-app
    tags: true